# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publishesr',
            new_name='publisher',
        ),
    ]
